-- 0003_rls.sql — (intentionally empty)
--
-- Row Level Security is intentionally NOT used in this project.
--
-- Why: the web app reads the database SERVER-SIDE ONLY (Next.js App Router
-- server components / route handlers) using a single DATABASE_URL credential
-- that is never exposed to the browser. There is no anonymous/publishable
-- client key reaching end users, so there is no untrusted role to constrain
-- with RLS.
--
-- Access control instead comes from the QUERIES themselves: every results
-- query hardcodes `where verification_status = 'published'`, so unpublished
-- (pending/held/refuted) rows never leave the server. Reference tables
-- (domains/tasks/benchmarks/methods/papers/code) hold no secrets.
--
-- This file is kept (rather than deleted) so migration numbering stays stable.
-- The migration runner tolerates an effectively-empty SQL file and skips it.
